[versions]
dokka = "1.9.20"
kotlin = "2.0.20"

[libraries]
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
